filter:
    excluded_paths: [vendor/*, Tests/*, bin/*, Resources/]
checks:
    php: true
tools:
    external_code_coverage:
        timeout: 600
    php_sim: true
    php_mess_detector: true
    php_cs_fixer: true
    php_analyzer: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_loc:
        enabled: true
        excluded_dirs:        [vendor]
    php_pdepend:
        enabled: true
        excluded_dirs:        [vendor, Tests, bin]