language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install: composer update --prefer-source

script: phpunit --coverage-clover=coverage.clover